FROM node:8-alpine

ENV APP_DIR /home/node/app
ENV NODE_ENV "production"

WORKDIR $APP_DIR

RUN apk add --update --no-cache --virtual .build-deps git \
		&& git clone https://github.com/cubedro/eth-net-intelligence-api.git . \
    && npm install --force \
    && npm cache clean --force  \
    && apk del .build-deps \
    && chown -R node:node ${APP_DIR}

USER node

CMD [ "npm", "start" ]
